
"""Generate sql_run.sql from CSV data (สร้างไฟล์ SQL สำหรับ seed)"""
# Example usage: python generate_sql_run.py
import csv
import os

# Configuration
BASE_DIR = 'server'
DATA_DIR = os.path.join(BASE_DIR, 'data')
SCHEMA_FILE = os.path.join(BASE_DIR, 'src', 'sql', '001_schema.sql')
OUTPUT_FILE = os.path.join(BASE_DIR, 'sql_run.sql')

# Column type definitions
# 'n' = number (no quotes), 's' = string (quotes), 't' = timestamp/date (quotes)
TABLE_SCHEMAS = {
    'country': {'id': 'n', 'created_at': 't', 'code': 's', 'name': 's'},
    'units': {'id': 'n', 'created_at': 't', 'code': 's', 'name': 's'},
    'customer': {'id': 'n', 'created_at': 't', 'code': 's', 'name': 's', 'address_line1': 's', 'address_line2': 's', 'country_id': 'n', 'credit_limit': 'n'},
    'product': {'id': 'n', 'created_at': 't', 'code': 's', 'name': 's', 'units_id': 'n', 'unit_price': 'n'},
    'invoice': {'id': 'n', 'created_at': 't', 'invoice_no': 's', 'invoice_date': 't', 'customer_id': 'n', 'total_amount': 'n', 'vat': 'n', 'amount_due': 'n'},
    'invoice_line_item': {'id': 'n', 'created_at': 't', 'invoice_id': 'n', 'product_id': 'n', 'quantity': 'n', 'unit_price': 'n', 'extended_price': 'n'}
}

def format_value(value, col_type):
    if value is None:
        return 'NULL'
    
    val_str = str(value).strip()
    
    # Handle NULL-like strings
    if val_str.lower() == 'null' or val_str == '':
        return 'NULL'

    # Remove existing quotes if present
    if (val_str.startswith("'") and val_str.endswith("'")):
        val_str = val_str[1:-1]
    
    if col_type == 'n':
        # Number format: ensure it's a valid number string or fallback to NULL if broken
        # Clean commas for numbers like 1,000,000
        val_str = val_str.replace(',', '')
        try:
            # Check if it's numeric/float
            float(val_str)
            return val_str
        except ValueError:
            # If not a number, maybe it's '-' or something, treat as NULL for numeric field
            return 'NULL'
    else:
        # String/Timestamp: Escape and wrap in quotes
        escaped = val_str.replace("'", "''")
        return f"'{escaped}'"

def get_insert_sql(table, csv_path, columns):
    statements = []
    if not os.path.exists(csv_path):
        print(f"Warning: File not found: {csv_path}")
        return []

    schema = TABLE_SCHEMAS.get(table, {})

    # Use utf-8-sig to handle UTF-8 with BOM
    with open(csv_path, 'r', encoding='utf-8-sig') as f:
        reader = csv.DictReader(f)
        
        # Debug: Print fieldnames to catch BOM issues
        # print(f"Processing {table}, fields found: {reader.fieldnames}")
        
        # Normalizing fieldnames to remove whitespace or weird characters
        if reader.fieldnames:
            reader.fieldnames = [fn.strip() for fn in reader.fieldnames]

        for row in reader:
            cols_to_insert = []
            vals_to_insert = []
            
            for col in columns:
                raw_val = row.get(col)
                
                col_type = schema.get(col, 's')
                formatted_val = format_value(raw_val, col_type)
                
                cols_to_insert.append(col)
                vals_to_insert.append(formatted_val)
            
            if cols_to_insert:
                stmt = f"INSERT INTO {table} ({', '.join(cols_to_insert)}) VALUES ({', '.join(vals_to_insert)});"
                statements.append(stmt)

    return statements

def main():
    content = []
    content.append("-- Auto-generated SQL script to setup schema and load data")
    content.append("-- Database: PostgreSQL (Docker)")
    content.append("")
    content.append("-- ==========================================")
    content.append("-- 1. Schema Creation")
    content.append("-- ==========================================")
    
    content.append("""
drop table if exists invoice_line_item;
drop table if exists invoice;
drop table if exists product;
drop table if exists customer;
drop table if exists units;
drop table if exists country;

create table country (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  code text unique not null,
  name text not null
);

create table units (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  code text unique not null,
  name text not null
);

create table customer (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  code text unique not null,
  name text not null,
  address_line1 text,
  address_line2 text,
  country_id bigint references country(id),
  credit_limit numeric(12,2)
);

create table product (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  code text unique not null,
  name text not null,
  units_id bigint references units(id),
  unit_price numeric(12,2)
);

create table invoice (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  invoice_no text unique not null,
  invoice_date date,
  customer_id bigint references customer(id),
  total_amount numeric(12,2),
  vat numeric(12,2),
  amount_due numeric(12,2)
);

create table invoice_line_item (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  invoice_id bigint not null references invoice(id) on delete cascade,
  product_id bigint not null references product(id),
  quantity numeric(12,2),
  unit_price numeric(12,2),
  extended_price numeric(12,2),
  unique (invoice_id, product_id)
);

create index if not exists idx_invoice_date on invoice(invoice_date);
create index if not exists idx_line_invoice on invoice_line_item(invoice_id);
create index if not exists idx_line_product on invoice_line_item(product_id);
""")
    content.append("\n")
    content.append("-- ==========================================")
    content.append("-- 2. Data Insertion")
    content.append("-- ==========================================")

    tables = [
        {
            'name': 'country',
            'file': 'country_test.csv',
            'cols': ['id', 'created_at', 'code', 'name']
        },
        {
            'name': 'units',
            'file': 'units_test.csv',
            'cols': ['id', 'created_at', 'code', 'name']
        },
        {
            'name': 'customer',
            'file': 'customer_test.csv',
            'cols': ['id', 'created_at', 'code', 'name', 'address_line1', 'address_line2', 'country_id', 'credit_limit']
        },
        {
            'name': 'product',
            'file': 'product_test.csv',
            'cols': ['id', 'created_at', 'code', 'name', 'units_id', 'unit_price']
        },
        {
            'name': 'invoice',
            'file': 'invoice_test.csv',
            'cols': ['id', 'created_at', 'invoice_no', 'invoice_date', 'customer_id', 'total_amount', 'vat', 'amount_due']
        },
        {
            'name': 'invoice_line_item',
            'file': 'invoice_line_item_test.csv',
            'cols': ['id', 'created_at', 'invoice_id', 'product_id', 'quantity', 'unit_price', 'extended_price']
        }
    ]

    for t in tables:
        content.append(f"\n-- Populating table: {t['name']}")
        csv_path = os.path.join(DATA_DIR, t['file'])
        inserts = get_insert_sql(t['name'], csv_path, t['cols'])
        content.extend(inserts)

    content.append("\n-- update sequences to max id (crutial when inserting explicit IDs)")
    for t in tables:
        tbl = t['name']
        content.append(f"SELECT setval(pg_get_serial_sequence('{tbl}', 'id'), coalesce(max(id),0) + 1, false) FROM {tbl};")

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write('\n'.join(content))
    
    print(f"Generated {OUTPUT_FILE} successfully.")

if __name__ == "__main__":
    main()
